import type { GuitarShapeDefinition } from "@/core/types";

export const GUITAR_BARRE_A_SHAPES: GuitarShapeDefinition[] = [
  {
    id: "barre-a-major",
    rootString: 5,
    quality: "major",
    type: "barre-a",
    movable: true,
    strings: ["x", 0, 2, 2, 2, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-5", "major"],
  },
  {
    id: "barre-a-minor",
    rootString: 5,
    quality: "minor",
    type: "barre-a",
    movable: true,
    strings: ["x", 0, 2, 2, 1, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-5", "minor"],
  },
  {
    id: "barre-a-dominant7",
    rootString: 5,
    quality: "dominant7",
    type: "barre-a",
    movable: true,
    strings: ["x", 0, 2, 0, 2, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-5", "dominant7"],
  },
  {
    id: "barre-a-maj7",
    rootString: 5,
    quality: "maj7",
    type: "barre-a",
    movable: true,
    strings: ["x", 0, 2, 1, 2, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-5", "maj7"],
  },
  {
    id: "barre-a-m7",
    rootString: 5,
    quality: "m7",
    type: "barre-a",
    movable: true,
    strings: ["x", 0, 2, 0, 1, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-5", "m7"],
  },
];