import type { ChordDefinition } from "./types";

export const CHORD_FORMULAS: ChordDefinition[] = [
  {
    id: "major",
    symbol: "",
    aliases: ["major", "mayor", "maj"],
    nameEs: "mayor",
    nameEn: "major",
    semitones: [0, 4, 7],
  },
  {
    id: "minor",
    symbol: "m",
    aliases: ["minor", "menor", "min", "m"],
    nameEs: "menor",
    nameEn: "minor",
    semitones: [0, 3, 7],
  },
  {
    id: "diminished",
    symbol: "dim",
    aliases: ["dim", "diminished", "disminuido"],
    nameEs: "disminuido",
    nameEn: "diminished",
    semitones: [0, 3, 6],
  },
  {
    id: "augmented",
    symbol: "aug",
    aliases: ["aug", "augmented", "aumentado"],
    nameEs: "aumentado",
    nameEn: "augmented",
    semitones: [0, 4, 8],
  },
  {
    id: "sus2",
    symbol: "sus2",
    aliases: ["sus2"],
    nameEs: "suspendido segunda",
    nameEn: "suspended second",
    semitones: [0, 2, 7],
  },
  {
    id: "sus4",
    symbol: "sus4",
    aliases: ["sus4"],
    nameEs: "suspendido cuarta",
    nameEn: "suspended fourth",
    semitones: [0, 5, 7],
  },
  {
    id: "maj7",
    symbol: "maj7",
    aliases: ["maj7", "major7", "major 7", "mayor 7"],
    nameEs: "séptima mayor",
    nameEn: "major seventh",
    semitones: [0, 4, 7, 11],
  },
  {
    id: "m7",
    symbol: "m7",
    aliases: ["m7", "min7", "minor7", "minor 7", "menor 7"],
    nameEs: "séptima menor",
    nameEn: "minor seventh",
    semitones: [0, 3, 7, 10],
  },
  {
    id: "dominant7",
    symbol: "7",
    aliases: ["7", "dom7", "dominant7", "dominante 7"],
    nameEs: "séptima dominante",
    nameEn: "dominant seventh",
    semitones: [0, 4, 7, 10],
  },
];