import type { GuitarShapeDefinition } from "@/core/types";

export const GUITAR_OPEN_SHAPES: GuitarShapeDefinition[] = [
  {
    id: "open-c-major",
    rootString: 5,
    quality: "major",
    type: "open",
    movable: false,
    strings: ["x", 3, 2, 0, 1, 0],
    usesBarre: false,
    tags: ["open", "common", "root-5"],
  },
  {
    id: "open-a-major",
    rootString: 5,
    quality: "major",
    type: "open",
    movable: false,
    strings: ["x", 0, 2, 2, 2, 0],
    usesBarre: false,
    tags: ["open", "common", "root-5"],
  },
  {
    id: "open-g-major",
    rootString: 6,
    quality: "major",
    type: "open",
    movable: false,
    strings: [3, 2, 0, 0, 0, 3],
    usesBarre: false,
    tags: ["open", "common", "root-6"],
  },
  {
    id: "open-e-major",
    rootString: 6,
    quality: "major",
    type: "open",
    movable: false,
    strings: [0, 2, 2, 1, 0, 0],
    usesBarre: false,
    tags: ["open", "common", "root-6"],
  },
  {
    id: "open-d-major",
    rootString: 4,
    quality: "major",
    type: "open",
    movable: false,
    strings: ["x", "x", 0, 2, 3, 2],
    usesBarre: false,
    tags: ["open", "common", "root-4"],
  },

  {
    id: "open-a-minor",
    rootString: 5,
    quality: "minor",
    type: "open",
    movable: false,
    strings: ["x", 0, 2, 2, 1, 0],
    usesBarre: false,
    tags: ["open", "common", "root-5"],
  },
  {
    id: "open-e-minor",
    rootString: 6,
    quality: "minor",
    type: "open",
    movable: false,
    strings: [0, 2, 2, 0, 0, 0],
    usesBarre: false,
    tags: ["open", "common", "root-6"],
  },
  {
    id: "open-d-minor",
    rootString: 4,
    quality: "minor",
    type: "open",
    movable: false,
    strings: ["x", "x", 0, 2, 3, 1],
    usesBarre: false,
    tags: ["open", "common", "root-4"],
  },

  {
    id: "open-c-maj7",
    rootString: 5,
    quality: "maj7",
    type: "open",
    movable: false,
    strings: ["x", 3, 2, 0, 0, 0],
    usesBarre: false,
    tags: ["open", "maj7", "common", "root-5"],
  },
  {
    id: "open-a-minor7",
    rootString: 5,
    quality: "m7",
    type: "open",
    movable: false,
    strings: ["x", 0, 2, 0, 1, 0],
    usesBarre: false,
    tags: ["open", "m7", "common", "root-5"],
  },
  {
    id: "open-e7",
    rootString: 6,
    quality: "dominant7",
    type: "open",
    movable: false,
    strings: [0, 2, 0, 1, 0, 0],
    usesBarre: false,
    tags: ["open", "dominant7", "common", "root-6"],
  },
  {
    id: "open-d7",
    rootString: 4,
    quality: "dominant7",
    type: "open",
    movable: false,
    strings: ["x", "x", 0, 2, 1, 2],
    usesBarre: false,
    tags: ["open", "dominant7", "common", "root-4"],
  },
];