import type { GuitarShapeDefinition } from "@/core/types";

export const GUITAR_BARRE_E_SHAPES: GuitarShapeDefinition[] = [
  {
    id: "barre-e-major",
    rootString: 6,
    quality: "major",
    type: "barre-e",
    movable: true,
    strings: [0, 2, 2, 1, 0, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-6", "major"],
  },
  {
    id: "barre-e-minor",
    rootString: 6,
    quality: "minor",
    type: "barre-e",
    movable: true,
    strings: [0, 2, 2, 0, 0, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-6", "minor"],
  },
  {
    id: "barre-e-dominant7",
    rootString: 6,
    quality: "dominant7",
    type: "barre-e",
    movable: true,
    strings: [0, 2, 0, 1, 0, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-6", "dominant7"],
  },
  {
    id: "barre-e-maj7",
    rootString: 6,
    quality: "maj7",
    type: "barre-e",
    movable: true,
    strings: [0, 2, 1, 1, 0, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-6", "maj7"],
  },
  {
    id: "barre-e-m7",
    rootString: 6,
    quality: "m7",
    type: "barre-e",
    movable: true,
    strings: [0, 2, 0, 0, 0, 0],
    usesBarre: true,
    tags: ["barre", "movable", "root-6", "m7"],
  },
];